### PR TITLE
Isac

### PR DESCRIPTION
**Pull request by earnone**
Merging of our final refinements looks smooth.

### CODE REVIEW

**Comment by earnone** [comment]
Please keep master in the three conflicts. Make sure reduced-size image in ensclus is maintained.

**Comment by earnone** [comment]
@nielsdrost sorry about that. Actually I have changed most references because they were not loaded previously as a list... Yes 3 paths to images were in conflict and should keep the master version.

**Comment by nielsdrost** [comment]
He @earnone, no problem at all, just making sure you know so that the errors don't keep sneaking up on us ;-)

See the result at http://portal.c3s-magic.eu/#/diagnostics now.

**Comment by earnone** [comment]
@nielsdrost I can see the descriptions.yml files were updated on the repository master branch but the portal website is still showing the old descriptions

**Pull request merged**
